version: '3'

services:
  etl:
    build:
      context: etl
      target: prod

  registration:
    build:
      context: filter/registration
      target: prod

  filter-worker-contract:
    build:
      context: filter/worker
      target: prod

  filter-worker-transaction:
    build:
      context: filter/worker
      target: prod

  rest-api:
    build:
      context: rest
      target: prod

  icon-graphql-api:
    build:
      context: graphql
      target: prod

  kafka-websocket-server:
    build:
      context: websockets/websocket
      target: prod

  icon-registration-websocket-server:
    build:
      context: websockets/registration-websocket
      target: prod
