
name: Dispatch - Run tests from outside trigger

on:
  repository_dispatch:
    types: [integration-tests]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - run: |
          pip3 install tackle-box
          tackle . --context-file repos.yml --no-input
          docker-compose -f docker-compose.yml -f docker-composer.dev.yml up -d
          
          