name: Rebuild docs

on:
  push:
    branches:
      - main
      - fix-docs

jobs:
  build:
    name: Push Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r docs/requirements.txt

      - name: Clone repos
        run: tackle . --context-file repos.yaml --no-input

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the stack
        run: docker-compose -f docker-compose.yml -f docker-compose.unit.yml up -d

      - name: Wait to stabilize and check running containers
        run: |
          sleep 120
          docker-compose -f docker-compose.yml -f docker-compose.unit.yml ps

      - name: Generate new openapi specs
        run: |
          curl localhost/api/v1/openapi.json > docs/openapi.rest.json
          curl localhost/api/v1/admin/docs/openapi.json > docs/openapi.registration.json

      - name: Symlink subrepo readmes
        run: |
          ln -s ../rest-api/README.md rest-api-readme.md
          ln -s ../etl/README.md etl-readme.md
          ln -s ../filter/registration/README.md filter-registration-readme.md
          ln -s ../filter/worker/README.md filter-worker-readme.md
          ln -s ../websockets/registration-websocket/README.md registration-websocket-readme.md
          ln -s ../websockets/websocket/README.md websocket-readme.md
          ln -s ../graphql/README.md graphql-readme.md

      - name: make the docs
        run: cd docs && make html && touch _build/html/.nojekyll

      - name: github pages deploy
        uses: peaceiris/actions-gh-pages@v2.3.1
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: docs/_build/html
