name: Push / PR integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: |
          pip3 install tackle-box
          tackle . --context-file repos.yml --no-input

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the stack
        run: docker-compose -f docker-compose.yml up -d

      - name: Check running containers
        run: docker-compose -f docker-compose.yml ps

      - name: Run test suite
        run: |
          sleep 60
          python -m pytest tests
