name: Push / PR unit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      SETUPTOOLS_USE_DISTUTILS: stdlib
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the stack
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d

      - name: Check running containers
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml ps

      - name: Check logs
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml logs rest

      - name: Run test suite
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml run rest pytest
